staging: zram: Rename devices to zram_devices
devices are defined somewhere else in the kernel, causing following error
when compiling zram:

error: drivers/built-in.o: multiple definition of 'devices'
arch/arm/mach-msm/built-in.o: previous definition here